### ISSUE TITLE
Use nearest flowline as #1 or only priority?

### ISSUE THREAD

**Issue by rviger** [dwief-usgs/hydrolink#2]
In many cases if the geospatial precision is known to be good it would be best to always select nearest flowline. Current methods only support name match as first criteria. Could create a 2nd list of points where the name match showed something different than the geometric analysis.

**Comment by dwief-usgs** [comment]
@rviger-usgs  HydroLink now allows user to work against 2 methods for both High Resolution and Medium Resolution datasets.  These options can also be accessed in the Hydrolinker command line tool as well.  

![image](https://user-images.githubusercontent.com/18450000/79346958-3e423a80-7ef0-11ea-8a85-e62d46eb7cfc.png)

**Comment by dwief-usgs** [comment]
included method parameter to allow user to select closest feature
