### ISSUE TITLE
Licensing confusion

### ISSUE THREAD

**Issue by skybristol** [dwief-usgs/hydrolink#4]
Your LICENSE file says its MIT, your readme says CC0, and the disclaimer is not exactly the USGS provisional software language that it should be. I've been using the GitHub-provided unlicense language, which essentially accomplishes the public domain donation better than CC0 in the case of software products.

**Comment by dwief-usgs** [comment]
@skybristol Thanks for pointing that out.  Using cookiecutter to improve the overall package, but looks like I missed a few things in putting that together but I updated license and USGS provisional text.  Let me know if you still see any issues.
